version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1

  db:
    image: sqlite:latest
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
