version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"  # Host:Container
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
    env_file:
      - .env  # Load environment variables from the .env file
    depends_on:
      - redis  # Ensure Redis starts before the web service
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
